### ISSUE TITLE
Support response.send_file for host servers without X-Sendfile support

### ISSUE THREAD

**Issue by rsms** [rsms/smisk#4]
By implementing something like

```
f = open(path, 'rb')
while not f.eof():
  response.out.write(f.read(8192))
f.close()
```

**Comment by greut** [comment]
I tried something, but it seems to primitive.

https://gist.github.com/1f9ec2af11cd4e7e06d8

The content get printed into the headers.

**Comment by rsms** [comment]
I'm considering including this in the next release. Just one thing I noticed while looking through it:

If this happens, NULL is returned...

```
if ( smisk_Stream_perform_write(self->out, line, PyBytes_Size(line)) == -1 ) {
    return NULL;
```

then Py_DECREF(line), PyFile_DecUseCount, fclose etc will not be called. You should probably do a goto, break the loop or dupe the finalization code.

On which python version(s) have you tried this? And, would you consider add this to your fork and send a push request? Please include the wsgi main patch[1] also, if you like.

[1] http://github.com/greut/smisk/commit/8844d8db3754dac29cd1488b6a24424b4353cec1
